server:
  port: 8081

spring:
  application:
    name: metrics-consumer
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ob11to
    password: ob11to
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
  cloud:
    stream:
      default:
        group: ${spring.application.name}
        content-type: application/json
      bindings:
        metricsTopic:
          destination: metrics-topic
      binders:
        kafka:
          environment:
            spring:
              kafka:
                consumer:
                  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:29092
          configuration:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        default:
          consumer:
            enableDlq: true
            autoCommitOnError: true
            autoCommitOffset: true
            dlqName: messages-with-errors-${spring.application.name}
            dlqProducerProperties:
              configuration:
                value:
                  serializer: org.apache.kafka.common.serialization.StringSerializer